name: 'Compile angular app'
description: 'Compile angular and copy dist folder to artifacts'

inputs:
  folder_project:
    description: 'folder name where the files are located. Example: /'
    required: false
    default: '/'
  baseHref:
    description: 'Base Href las flags del comando de angular para compilar. Ejemplo: lo ingresado debe iniciar con / '
    required: false
    default: '/'
    
  node-version:
    description: 'Node Version'
    required: true
    default: '18.x'

  configuration:
    description: 'Configuration of angular build. Example: development or production. Default: production'
    required: false
    default: 'production'

runs:
  using: 'composite'
  steps:
    #Se debe instalar la version de node que se va a utilizar
    - name: Setup Node ${{ inputs.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ inputs.node-version }}

    #poner el comando para las banderas de instalacion
    - name: Install Dependencies
      shell: bash
      run: |
        echo "Instalando dependencias..."
        yarn install

    - name: Build Angular App
      shell: bash
      run: |
        echo "Compilando Aplicacion en la carpeta ${{ inputs.folder_project }}..."
        cd ${{ inputs.folder_project }}
        yarn build --configuration=${{ inputs.configuration }} --base-href=${{ inputs.baseHref }}/

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: dist