name: 'Deploy to Server'
description: 'Deploy to Server with SSH connection and SCP'

inputs:
  folder:
    description: 'folder name where the files are located'
    required: true
    default: 'dist'
  target:
    description: 'target folder name where the files are located'
    required: true
    default: 'pages'

runs:
  using: 'composite'
  steps:
    - name: Build Angular App
      run: |
        echo "Comprimiendo archivos..."
        tar -czf dist-${{ github.sha }}.tgz ${{ inputs.folder }}

    - name: Load to Server
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: dist-${{ github.sha }}.tgz
        target: ~/${{ inputs.target }}
    
    - name: Deploy on Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd ~/${{ inputs.target }}
          rm -r ${{ env.outputPath }}
          tar -xzf dist-${{ github.sha }}.tgz --strip-components=1
          rm dist-${{ github.sha }}.tgz