name: Angular compile and compress

on:
  workflow_call:
    inputs:
      baseHref:
        description: 'Base Href'
        type: string
        required: true
        default: '/'
      nodeVersion:
        description: 'Node Version'
        type: string
        required: true
        default: '16.x'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ inputs.nodeVersion }}

      - name: Install Dependencies
        run: yarn install --force

      #compilando el proyecto y comprimiendo los archivos.
      - name: Build Angular App
        run: |
          yarn run build --configuration=production --base-href=/${{ inputs.baseHref }}/
          
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist
